### ISSUE TITLE
Backend Setup

### ISSUE THREAD

**Issue by Nish7** [Nish7/nish7.io#8]
## Database Entities:
1. Posts
2. Stack
3. Bookmarks
4. Technologies
5. ...things in misc

## Links 
- [MDX](https://mdxjs.com/docs/getting-started/)
- [Leerob Ref](https://github.com/leerob/leerob.io/blob/main/pages/blog/%5Bslug%5D.tsx)
- [MDX Blog](https://www.joshwcomeau.com/blog/how-i-built-my-blog/)
- [MDX Remote](https://github.com/hashicorp/next-mdx-remote)

Notes:
- How to give enum type in supabase database? For example, type field should be limited to certain options only.
- How to check the link type in the field. should be in correct link format.
- create a slug base on the blog title or name.
- research frontmatter and blogpost metadata

## Todo:
- [x] watch Supabase crash course
- [x] Set up fake data in the supabase
  - [x] 5 posts (Cancelled)
  - [x] 10 Stack
  - [x] 10 Bookmarks
  - [x] 5 Random Projects
  - [x] 10 Technologies
- [x] Connect backend to the client
